brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "btop"
brew "coreutils"
brew "ffmpeg" # because it's always handy
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "gitleaks"
brew "gum"
brew "lazydocker"
brew "mise"
brew "neovim"
brew "opencode"
brew "pstree"
brew "poppler" # pdf tools for codex
brew "ripgrep"
brew "screen"
brew "shellcheck"
brew "starship"
brew "stow"
brew "tmux"
brew "uv"
brew "watch"
brew "yt-dlp"
brew "zoxide"

cask "1password-cli"
cask "bartender"
cask "cleanshot"
cask "claude-code"
cask "codex"
cask "docker-desktop"
cask "fantastical"
cask "forklift"
cask "ghostty"
cask "hazeover"
cask "hopper-disassembler"
cask "iina"
cask "istat-menus"
cask "libreoffice-still" # for https://github.com/anthropics/skills/blob/main/skills/xlsx/SKILL.md
cask "linearmouse"
cask "opencode-desktop"
cask "rectangle-pro"
cask "soundsource"
cask "sublime-text"
cask "thaw"

# work
brew "hashicorp/tap/terraform", trusted: true
cask "terraform-linters/tap/tflint", trusted: true
