brew "awscli"
brew "bash-completion@2"
brew "bat"
brew "btop"
brew "coreutils"
brew "ffmpeg" # because it's always handy
brew "fzf"
brew "neovim"
brew "pstree"
brew "poppler" # pdf tools for codex
brew "screen"
brew "starship"
brew "tmux"
brew "uv"
brew "watch"
brew "yt-dlp"
brew "zoxide"

cask "1password-cli"
cask "alfred"
cask "bartender"
cask "betterdisplay"
cask "chatgpt"
cask "cleanshot"
cask "claude-code"
cask "codex"
cask "fantastical"
cask "forklift"
cask "ghostty"
cask "google-chrome"
cask "hazeover"
cask "hopper-disassembler"
cask "iina"
cask "istat-menus"
cask "jetbrains-toolbox"
cask "libreoffice-still" # for https://github.com/anthropics/skills/blob/main/skills/xlsx/SKILL.md
cask "linearmouse"
cask "mimestream"
cask "obsidian"
cask "orbstack"
cask "rectangle-pro"
cask "slack"
cask "soundsource"
cask "sublime-text"
cask "tuna"
cask "typora"
cask "visual-studio-code"

mas "Clocker", id: 1056643111
mas "iA Writer", id: 775737590
mas "Things 3", id: 904280696
