[tools]
gitleaks = "8.30.1"
hk = { version = "2.0.1", postinstall = "hk install --mise" }
taplo = "latest"

[env]
_.path = ["./bin"]

[tasks.lint]
description = "Run all lint checks"
run = "hk check --all --verbose"
